### ISSUE TITLE
cannot load data when length of the depth dimension is 0 or 1

### ISSUE THREAD

**Issue by jk-rieck** [willirath/xorca#12]
This becomes problematic, when you have surface data (e.g. SSH) and this is stored in a separate file. Depending on whether you directly let that file be written as model output or how you generate this file in the postprocessing, the file will have either no depth dimension or a depth dimension of length 1. If it has length 1, it will be squeezed away with `trim_and_squeeze()` so that in both cases, you end up with no depth dimension. However, the code fails at various lines because of the missing depth dimension afterwards... 

I think, there are two possibilities: 

1) we only treat data with a depth dimension and change `trim_and_squeeze()` so it doesn't get squeezed away

2) we allow data without a depth dimension, which would result in the need to go have a lot more changes to the code. And thinking of it now... if we allow data without a depth dimension, we might also want to allow data without a time dimension and so on...

I'd say, option one is easier and quicker to implement and thus preferable.

**Comment by willirath** [comment]
Solved with #13.
