### ISSUE TITLE
Vertical velocity missing in orca_names.py

### ISSUE THREAD

**Issue by swantjebastin** [willirath/xorca#16]
Vertical velocity (vovecrtz) could be added to orca_names.py since it is a fairly standard variable...

**Comment by willirath** [comment]
We should definitely to this. For the moment, you can add arbitrary bars using the method outlined here: https://gist.github.com/willirath/301225aec5c6776a40be31e0a66e2f73

**Comment by willirath** [comment]
@swantjebastin It would be great if you could add this to the dictionary. Just edit the file directly on github. This will automatically fork the repository, create a new branch in your fork, and propose a pull request here.

**Comment by swantjebastin** [comment]
I've added the vertical velocity (see pull request).

**Comment by willirath** [comment]
closed with #17
