### ISSUE TITLE
Use equality checks instead of identity checks

### ISSUE THREAD

**Issue by willirath** [willirath/xorca#24]
https://github.com/willirath/xorca/blob/1b1900deddf98d983d649e948d642bb511fbb7e8/xorca/tests/test_mesh_mask.py#L138

should use  `... != "t"` instead of `is not`.

@jk-rieck can you also fix this? I'd then issue a new release asap.

**Comment by jk-rieck** [comment]
only at this location, or should I look into the other files as well? for example here: https://github.com/willirath/xorca/blob/master/xorca/lib.py#L57

**Comment by willirath** [comment]
I think only there. At least that's the sole place where flake complained.

**Comment by jk-rieck** [comment]
See #25

**Comment by willirath** [comment]
Fixed in #25
