### ISSUE TITLE
The `inplace` argument has been removed from xarray.

### ISSUE THREAD

**Issue by sryan288** [willirath/xorca#28]
Hi everyone,

I had to install XORCA on a new machine and with that installed the newest version of xarray and it turns out that it produces an error when using load_xorca_dataset. This seems to be due to the fact that the 'inplace' argument has been removed from xarray in the new version. I removed the argument in the ds.set_coords function in lib.py, which seems to fix the problem. So maybe this should be updated in the XORCA code. I added the error message below for completeness:

`
ds_xorca = load_xorca_dataset(data_files=data_files, aux_files=aux_files)

CPU times: user 5 µs, sys: 3 µs, total: 8 µs
Wall time: 16.5 µs

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-95405cbc30da> in <module>
      1 get_ipython().run_line_magic('time', '')
      2 #%memit
----> 3 ds_xorca = load_xorca_dataset(data_files=data_files, aux_files=aux_files)

~/miniconda3/envs/xorca_env/lib/python3.7/site-packages/xorca/lib.py in load_xorca_dataset(data_files, aux_files, decode_cf, **kwargs)
    405                     **kwargs),
    406                     data_files, _data_files_chunks)),
--> 407             key=_get_first_time_step_if_any))
    408 
    409     # Add info from aux files

~/miniconda3/envs/xorca_env/lib/python3.7/site-packages/xorca/lib.py in <lambda>(ds)
    400         sorted(
    401             map(
--> 402                 lambda ds: preprocess_orca(aux_ds, ds, **kwargs),
    403                 map(lambda df, chunks: rename_dims(
    404                     xr.open_dataset(df, chunks=chunks, decode_cf=decode_cf),

~/miniconda3/envs/xorca_env/lib/python3.7/site-packages/xorca/lib.py in preprocess_orca(mesh_mask, ds, **kwargs)
    321 
    322     # make everything that does not depend on time a coord
--> 323     return_ds = set_time_independent_vars_to_coords(return_ds)
    324 
    325     return return_ds

~/miniconda3/envs/xorca_env/lib/python3.7/site-packages/xorca/lib.py in set_time_independent_vars_to_coords(ds)
    264     return ds.set_coords([v for v in ds.data_vars.keys()
    265                           if 't' not in ds[v].dims],
--> 266                          inplace=False)
    267 
    268 

~/miniconda3/envs/xorca_env/lib/python3.7/site-packages/xarray/core/dataset.py in set_coords(self, names, inplace)
   1384         # nb. check in self._variables, not self.data_vars to insure that the
   1385         # operation is idempotent
-> 1386         _check_inplace(inplace)
   1387         if isinstance(names, str) or not isinstance(names, Iterable):
   1388             names = [names]

~/miniconda3/envs/xorca_env/lib/python3.7/site-packages/xarray/core/utils.py in _check_inplace(inplace)
     38     if inplace is not None:
     39         raise TypeError(
---> 40             "The `inplace` argument has been removed from xarray. "
     41             "You can achieve an identical effect with python's standard assignment."
     42         )

TypeError: The `inplace` argument has been removed from xarray. You can achieve an identical effect with python's standard assignment.

`

**Comment by willirath** [comment]
This is also #14 

I'll fix this.

**Comment by willirath** [comment]
Fixed with #29.
