### ISSUE TITLE
`auto_combine` will be deprecated in xarray v0.15

### ISSUE THREAD

**Issue by christophrenkl** [willirath/xorca#30]
First off, thanks a lot for writing this package! I'm current looking into using `xgcm` for analyzing my NEMO output, so I think `xorca` will save me a lot of headache to prepare my files.

During my first attempt using `xorca`, I ran into
```
FutureWarning: In xarray version 0.15 `auto_combine` will be deprecated. See
http://xarray.pydata.org/en/stable/combining.html#combining-multi
```
I will shortly submit a pull request that should solve this warning by replacing `auto_combine` with `combine_by_coords`. Hopefully this will make this package compatible with future versions of `xarray`.

**Comment by willirath** [comment]
Closed with #32.  Thanks @christophrenkl !
