### ISSUE TITLE
Read data with NEMO 4.0, z coordinate absent of mesh_mask file

### ISSUE THREAD

**Issue by rcaneill** [willirath/xorca#40]
Hello,

it seems that from the version 4.0 of NEMO the mesh_mask dimension in the vertical is `nav_lev` and not `z`. I use a test case where all the domain is defined in the usr_def files and then output by NEMO.

The absence of the `z` dimension breaks the opening of the output files with `load_xorca_dataset` in the function `create_minimal_coords_ds`, as `"z"` is not a dimension (a `KeyError`is raised at line 89):
https://github.com/willirath/xorca/blob/9ccbfb6fc880247b71503c12417e1e284e5738a8/xorca/lib.py#L89

I coded a very simple patch like following, if appropriated I can submit a PR for this.

```python
def create_minimal_coords_ds(mesh_mask, **kwargs):
    """Create a minimal set of coordinates from a mesh-mask dataset.

    This creates `"central"` and `"right"` grid points for the horizontal grid
    and `"central"` and `"left"` grid points in the vertical.

    """
    try:
        N_z = len(mesh_mask.coords["z"])
    except KeyError:
        N_z = len(mesh_mask.coords["nav_lev"])
    N_y = len(mesh_mask.coords["y"])
    N_x = len(mesh_mask.coords["x"])

    [...]
```

Attached is the output of `ncdump -h` with the mesh_mask.nc file, with an extract here:
```
dimensions:
	x = 20 ;
	y = 40 ;
	nav_lev = 36 ;
	time_counter = UNLIMITED ; // (1 currently)
variables:
	float nav_lon(y, x) ;
	float nav_lat(y, x) ;
	float nav_lev(nav_lev) ;
        [...]
```

[xorca_issue_mesh_mask.txt](https://github.com/willirath/xorca/files/6003758/xorca_issue_mesh_mask.txt)

**Comment by willirath** [comment]
Hi @rcaneill, thanks for wanting to contribute here. A PR would be very welcome!

While you’re  here: [This notebook](https://nbviewer.jupyter.org/github/ESM-VFC/esm-vfc-workflows/blob/f11545feac6ac8140ec9f31426feb696bdd28960/nemo_cf_demo/nemo_cf_demo.ipynb) shows some tests I’m doing (too busy with other things, however…) for autodetecting most of the grid specifics. Ideally, I'd like to really strip down Xorca to the bare minimum of hard-coded variable names etc.

If you have any NEMO 4 example data, it could be a good thing to post them on Zenodo. I've done so with 
- https://zenodo.org/record/3755721
- https://zenodo.org/record/3755517
- https://zenodo.org/record/3634491
to have an easy way of referring to some representative data and to have something (smallish) I can pull in for testing and demos.

**Comment by willirath** [comment]
Something I'd love to go for is to isolate the part that transforms Xarray Datasets with NEMO grid and mesh data into XGCM-compatible Xarray datasets from the data loading part. This way, we'd be a lot more flexible to use NEMO data in any format we'd like. (There's many people looking into transforming NEMO data to, e.g., Zarr or other things for making it cloud-ready. So the more format agnostic the tool is, the better!)

**Comment by rcaneill** [comment]
I'll have a proper look on the notebook next week.
For the detection of the position of the variables, I am using the filename (grid_T for T points, grid_U for U point, etc), which seemed to be the easiest for me. That's what I do in the package  [xnemogcm](https://github.com/rcaneill/xnemogcm) I developed before hearing of xorca.

I have a ~120MB test dataset, I can upload it to zenodo if you're interested to have them. They are in an idealized basin, terrain following coordinates with non flat-bottom.
